// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AgentManagerInterface.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::edu::rice::republic::amif;

class AgentManagerInterfaceHandler : virtual public AgentManagerInterfaceIf {
 public:
  AgentManagerInterfaceHandler() {
    // Your initialization goes here
  }

  void request(Response& _return, const Request& rq) {
    // Your implementation goes here
    printf("request\n");
  }

  void release(const Release& rl) {
    // Your implementation goes here
    printf("release\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<AgentManagerInterfaceHandler> handler(new AgentManagerInterfaceHandler());
  shared_ptr<TProcessor> processor(new AgentManagerInterfaceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

