/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "republic_constants.h"

namespace edu { namespace rice { namespace republic { namespace amif {

const republicConstants g_republic_constants;

republicConstants::republicConstants() {
}

}}}} // namespace

