/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef republic_CONSTANTS_H
#define republic_CONSTANTS_H

#include "republic_types.h"

namespace edu { namespace rice { namespace republic { namespace amif {

class republicConstants {
 public:
  republicConstants();

};

extern const republicConstants g_republic_constants;

}}}} // namespace

#endif
