/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include <math.h>

#include "edu_rice_republic_amif_republic_types.h"
#include <thrift/c_glib/thrift.h>

/* return the name of the constant */
const char *
toString_ResponseType(int value) 
{
  static __thread char buf[16] = {0};
  switch(value) {
  case EDU_RICE_REPUBLIC_AMIF_RESPONSE_TYPE_ACCEPT:return "EDU_RICE_REPUBLIC_AMIF_RESPONSE_TYPE_ACCEPT";
  case EDU_RICE_REPUBLIC_AMIF_RESPONSE_TYPE_DENY:return "EDU_RICE_REPUBLIC_AMIF_RESPONSE_TYPE_DENY";
  default: g_snprintf(buf, 16, "%d", value); return buf;
  }
}

enum _edu_rice_republic_amifRequestProperties
{
  PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_0,
  PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_RID,
  PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_AID,
  PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_DID,
  PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_DATASIZE,
  PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_REMAININGSIZE,
  PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_SENDER,
  PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_RECEIVERS
};

/* reads a request object */
static gint32
edu_rice_republic_amif_request_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_republic_amifRequest * this_object = EDU_RICE_REPUBLIC_AMIF_REQUEST(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRING)
        {
          if (this_object->rid != NULL)
          {
            g_free(this_object->rid);
            this_object->rid = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->rid, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_rid = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_STRING)
        {
          if (this_object->aid != NULL)
          {
            g_free(this_object->aid);
            this_object->aid = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->aid, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_aid = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 3:
        if (ftype == T_STRING)
        {
          if (this_object->did != NULL)
          {
            g_free(this_object->did);
            this_object->did = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->did, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_did = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 4:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->datasize, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_datasize = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 5:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->remainingsize, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_remainingsize = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 6:
        if (ftype == T_STRING)
        {
          if (this_object->sender != NULL)
          {
            g_free(this_object->sender);
            this_object->sender = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->sender, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_sender = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 7:
        if (ftype == T_SET)
        {
          {
            guint32 size;
            guint32 i;
            ThriftType element_type;

            if ((ret = thrift_protocol_read_set_begin (protocol, &element_type, &size, error)) < 0)
              return -1;
            xfer += ret;

            /* iterate through the set elements */
            for (i = 0; i < size; ++i)
            {
              edu_rice_republic_amifServerID _elem0 = NULL;
              if (_elem0 != NULL)
              {
                g_free(_elem0);
                _elem0 = NULL;
              }

              if ((ret = thrift_protocol_read_string (protocol, &_elem0, error)) < 0)
                return -1;
              xfer += ret;
              g_hash_table_insert ((GHashTable *) this_object->receivers, (gpointer) _elem0, (gpointer) 1);
            }
            if ((ret = thrift_protocol_read_set_end (protocol, error)) < 0)
              return -1;
            xfer += ret;

          }
          this_object->__isset_receivers = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_republic_amif_request_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_republic_amifRequest * this_object = EDU_RICE_REPUBLIC_AMIF_REQUEST(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "Request", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "rid", T_STRING, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->rid, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "aid", T_STRING, 2, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->aid, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "did", T_STRING, 3, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->did, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "datasize", T_I64, 4, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->datasize, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "remainingsize", T_I64, 5, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->remainingsize, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "sender", T_STRING, 6, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->sender, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "receivers", T_SET, 7, error)) < 0)
    return -1;
  xfer += ret;
  {
    GList *key_list = NULL, *iter = NULL;
    edu_rice_republic_amifServerID* keys;
    int i = 0, key_count;
    edu_rice_republic_amifServerID elem;
    gpointer value;
    THRIFT_UNUSED_VAR (value);

    if ((ret = thrift_protocol_write_set_begin (protocol, T_STRING, (gint32) g_hash_table_size ((GHashTable *) this_object->receivers), error)) < 0)
      return -1;
    xfer += ret;
    g_hash_table_foreach ((GHashTable *) this_object->receivers, thrift_hash_table_get_keys, &key_list);
    key_count = g_list_length (key_list);
    keys = g_newa (edu_rice_republic_amifServerID, key_count);
    for (iter = g_list_first (key_list); iter; iter = iter->next)
      keys[i++] = (edu_rice_republic_amifServerID) iter->data;
    g_list_free (key_list);

    for (i = 0; i < key_count; ++i)
    {
      elem = keys[i];
      value = (gpointer) g_hash_table_lookup (((GHashTable *) this_object->receivers), (gpointer) elem);

      if ((ret = thrift_protocol_write_string (protocol, elem, error)) < 0)
        return -1;
    }
    if ((ret = thrift_protocol_write_set_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_republic_amif_request_set_property (GObject *object,
                                             guint property_id,
                                             const GValue *value,
                                             GParamSpec *pspec)
{
  edu_rice_republic_amifRequest *self = EDU_RICE_REPUBLIC_AMIF_REQUEST (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_RID:
      if (self->rid != NULL)
        g_free (self->rid);
      self->rid = g_value_dup_string (value);
      self->__isset_rid = TRUE;
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_AID:
      if (self->aid != NULL)
        g_free (self->aid);
      self->aid = g_value_dup_string (value);
      self->__isset_aid = TRUE;
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_DID:
      if (self->did != NULL)
        g_free (self->did);
      self->did = g_value_dup_string (value);
      self->__isset_did = TRUE;
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_DATASIZE:
      self->datasize = g_value_get_int64 (value);
      self->__isset_datasize = TRUE;
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_REMAININGSIZE:
      self->remainingsize = g_value_get_int64 (value);
      self->__isset_remainingsize = TRUE;
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_SENDER:
      if (self->sender != NULL)
        g_free (self->sender);
      self->sender = g_value_dup_string (value);
      self->__isset_sender = TRUE;
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_RECEIVERS:
      if (self->receivers != NULL)
        g_hash_table_unref (self->receivers);
      self->receivers = g_value_dup_boxed (value);
      self->__isset_receivers = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_republic_amif_request_get_property (GObject *object,
                                             guint property_id,
                                             GValue *value,
                                             GParamSpec *pspec)
{
  edu_rice_republic_amifRequest *self = EDU_RICE_REPUBLIC_AMIF_REQUEST (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_RID:
      g_value_set_string (value, self->rid);
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_AID:
      g_value_set_string (value, self->aid);
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_DID:
      g_value_set_string (value, self->did);
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_DATASIZE:
      g_value_set_int64 (value, self->datasize);
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_REMAININGSIZE:
      g_value_set_int64 (value, self->remainingsize);
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_SENDER:
      g_value_set_string (value, self->sender);
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_RECEIVERS:
      g_value_set_boxed (value, self->receivers);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_republic_amif_request_instance_init (edu_rice_republic_amifRequest * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->rid = NULL;
  object->__isset_rid = FALSE;
  object->aid = NULL;
  object->__isset_aid = FALSE;
  object->did = NULL;
  object->__isset_did = FALSE;
  object->datasize = 0;
  object->__isset_datasize = FALSE;
  object->remainingsize = 0;
  object->__isset_remainingsize = FALSE;
  object->sender = NULL;
  object->__isset_sender = FALSE;
  object->receivers = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, NULL);
  object->__isset_receivers = FALSE;
}

static void 
edu_rice_republic_amif_request_finalize (GObject *object)
{
  edu_rice_republic_amifRequest *tobject = EDU_RICE_REPUBLIC_AMIF_REQUEST (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->rid != NULL)
  {
    g_free(tobject->rid);
    tobject->rid = NULL;
  }
  if (tobject->aid != NULL)
  {
    g_free(tobject->aid);
    tobject->aid = NULL;
  }
  if (tobject->did != NULL)
  {
    g_free(tobject->did);
    tobject->did = NULL;
  }
  if (tobject->sender != NULL)
  {
    g_free(tobject->sender);
    tobject->sender = NULL;
  }
  if (tobject->receivers != NULL)
  {
    g_hash_table_destroy (tobject->receivers);
    tobject->receivers = NULL;
  }
}

static void
edu_rice_republic_amif_request_class_init (edu_rice_republic_amifRequestClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_republic_amif_request_read;
  struct_class->write = edu_rice_republic_amif_request_write;

  gobject_class->finalize = edu_rice_republic_amif_request_finalize;
  gobject_class->get_property = edu_rice_republic_amif_request_get_property;
  gobject_class->set_property = edu_rice_republic_amif_request_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_RID,
     g_param_spec_string ("rid",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_AID,
     g_param_spec_string ("aid",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_DID,
     g_param_spec_string ("did",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_DATASIZE,
     g_param_spec_int64 ("datasize",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_REMAININGSIZE,
     g_param_spec_int64 ("remainingsize",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_SENDER,
     g_param_spec_string ("sender",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_REQUEST_RECEIVERS,
     g_param_spec_boxed ("receivers",
                         NULL,
                         NULL,
                         G_TYPE_HASH_TABLE,
                         G_PARAM_READWRITE));
}

GType
edu_rice_republic_amif_request_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_republic_amifRequestClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_republic_amif_request_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_republic_amifRequest),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_republic_amif_request_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_republic_amifRequestType",
                                   &type_info, 0);
  }

  return type;
}

enum _edu_rice_republic_amifResponseProperties
{
  PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_0,
  PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_RID,
  PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_TYPE,
  PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_CODE,
  PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_ACCEPTEDSIZE
};

/* reads a response object */
static gint32
edu_rice_republic_amif_response_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_republic_amifResponse * this_object = EDU_RICE_REPUBLIC_AMIF_RESPONSE(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRING)
        {
          if (this_object->rid != NULL)
          {
            g_free(this_object->rid);
            this_object->rid = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->rid, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_rid = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_I32)
        {
          gint32 ecast1;
          if ((ret = thrift_protocol_read_i32 (protocol, &ecast1, error)) < 0)
            return -1;
          xfer += ret;
          this_object->type = (edu_rice_republic_amifResponseType)ecast1;
          this_object->__isset_type = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 3:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->code, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_code = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 4:
        if (ftype == T_I64)
        {
          if ((ret = thrift_protocol_read_i64 (protocol, &this_object->acceptedsize, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_acceptedsize = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_republic_amif_response_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_republic_amifResponse * this_object = EDU_RICE_REPUBLIC_AMIF_RESPONSE(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "Response", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "rid", T_STRING, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->rid, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "type", T_I32, 2, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i32 (protocol, (gint32) this_object->type, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "code", T_I64, 3, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->code, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "acceptedsize", T_I64, 4, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i64 (protocol, this_object->acceptedsize, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_republic_amif_response_set_property (GObject *object,
                                              guint property_id,
                                              const GValue *value,
                                              GParamSpec *pspec)
{
  edu_rice_republic_amifResponse *self = EDU_RICE_REPUBLIC_AMIF_RESPONSE (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_RID:
      if (self->rid != NULL)
        g_free (self->rid);
      self->rid = g_value_dup_string (value);
      self->__isset_rid = TRUE;
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_TYPE:
      self->type = g_value_get_int (value);
      self->__isset_type = TRUE;
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_CODE:
      self->code = g_value_get_int64 (value);
      self->__isset_code = TRUE;
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_ACCEPTEDSIZE:
      self->acceptedsize = g_value_get_int64 (value);
      self->__isset_acceptedsize = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_republic_amif_response_get_property (GObject *object,
                                              guint property_id,
                                              GValue *value,
                                              GParamSpec *pspec)
{
  edu_rice_republic_amifResponse *self = EDU_RICE_REPUBLIC_AMIF_RESPONSE (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_RID:
      g_value_set_string (value, self->rid);
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_TYPE:
      g_value_set_int (value, self->type);
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_CODE:
      g_value_set_int64 (value, self->code);
      break;

    case PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_ACCEPTEDSIZE:
      g_value_set_int64 (value, self->acceptedsize);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_republic_amif_response_instance_init (edu_rice_republic_amifResponse * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->rid = NULL;
  object->__isset_rid = FALSE;
  object->__isset_type = FALSE;
  object->code = 0;
  object->__isset_code = FALSE;
  object->acceptedsize = 0;
  object->__isset_acceptedsize = FALSE;
}

static void 
edu_rice_republic_amif_response_finalize (GObject *object)
{
  edu_rice_republic_amifResponse *tobject = EDU_RICE_REPUBLIC_AMIF_RESPONSE (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->rid != NULL)
  {
    g_free(tobject->rid);
    tobject->rid = NULL;
  }
}

static void
edu_rice_republic_amif_response_class_init (edu_rice_republic_amifResponseClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_republic_amif_response_read;
  struct_class->write = edu_rice_republic_amif_response_write;

  gobject_class->finalize = edu_rice_republic_amif_response_finalize;
  gobject_class->get_property = edu_rice_republic_amif_response_get_property;
  gobject_class->set_property = edu_rice_republic_amif_response_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_RID,
     g_param_spec_string ("rid",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_TYPE,
     g_param_spec_int ("type",
                       NULL,
                       NULL,
                       0,
                       1,
                       0,
                       G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_CODE,
     g_param_spec_int64 ("code",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_RESPONSE_ACCEPTEDSIZE,
     g_param_spec_int64 ("acceptedsize",
                         NULL,
                         NULL,
                         G_MININT64,
                         G_MAXINT64,
                         0,
                         G_PARAM_READWRITE));
}

GType
edu_rice_republic_amif_response_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_republic_amifResponseClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_republic_amif_response_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_republic_amifResponse),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_republic_amif_response_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_republic_amifResponseType",
                                   &type_info, 0);
  }

  return type;
}

enum _edu_rice_republic_amifReleaseProperties
{
  PROP_EDU_RICE_REPUBLIC_AMIF_RELEASE_0,
  PROP_EDU_RICE_REPUBLIC_AMIF_RELEASE_RID
};

/* reads a release object */
static gint32
edu_rice_republic_amif_release_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_republic_amifRelease * this_object = EDU_RICE_REPUBLIC_AMIF_RELEASE(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRING)
        {
          if (this_object->rid != NULL)
          {
            g_free(this_object->rid);
            this_object->rid = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->rid, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_rid = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_republic_amif_release_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_republic_amifRelease * this_object = EDU_RICE_REPUBLIC_AMIF_RELEASE(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "Release", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "rid", T_STRING, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->rid, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_republic_amif_release_set_property (GObject *object,
                                             guint property_id,
                                             const GValue *value,
                                             GParamSpec *pspec)
{
  edu_rice_republic_amifRelease *self = EDU_RICE_REPUBLIC_AMIF_RELEASE (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_RELEASE_RID:
      if (self->rid != NULL)
        g_free (self->rid);
      self->rid = g_value_dup_string (value);
      self->__isset_rid = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_republic_amif_release_get_property (GObject *object,
                                             guint property_id,
                                             GValue *value,
                                             GParamSpec *pspec)
{
  edu_rice_republic_amifRelease *self = EDU_RICE_REPUBLIC_AMIF_RELEASE (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_RELEASE_RID:
      g_value_set_string (value, self->rid);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_republic_amif_release_instance_init (edu_rice_republic_amifRelease * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->rid = NULL;
  object->__isset_rid = FALSE;
}

static void 
edu_rice_republic_amif_release_finalize (GObject *object)
{
  edu_rice_republic_amifRelease *tobject = EDU_RICE_REPUBLIC_AMIF_RELEASE (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->rid != NULL)
  {
    g_free(tobject->rid);
    tobject->rid = NULL;
  }
}

static void
edu_rice_republic_amif_release_class_init (edu_rice_republic_amifReleaseClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_republic_amif_release_read;
  struct_class->write = edu_rice_republic_amif_release_write;

  gobject_class->finalize = edu_rice_republic_amif_release_finalize;
  gobject_class->get_property = edu_rice_republic_amif_release_get_property;
  gobject_class->set_property = edu_rice_republic_amif_release_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_RELEASE_RID,
     g_param_spec_string ("rid",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));
}

GType
edu_rice_republic_amif_release_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_republic_amifReleaseClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_republic_amif_release_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_republic_amifRelease),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_republic_amif_release_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_republic_amifReleaseType",
                                   &type_info, 0);
  }

  return type;
}

/* constants */

enum _edu_rice_republic_amifAgentManagerInterfaceRequestArgsProperties
{
  PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS_0,
  PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS_RQ
};

/* reads a agent_manager_interface_request_args object */
static gint32
edu_rice_republic_amif_agent_manager_interface_request_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_republic_amifAgentManagerInterfaceRequestArgs * this_object = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRUCT)
        {
          if ((ret = thrift_struct_read (THRIFT_STRUCT (this_object->rq), protocol, error)) < 0)
          {
            return -1;
          }
          xfer += ret;
          this_object->__isset_rq = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_republic_amif_agent_manager_interface_request_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_republic_amifAgentManagerInterfaceRequestArgs * this_object = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "AgentManagerInterfaceRequestArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "rq", T_STRUCT, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_struct_write (THRIFT_STRUCT (this_object->rq), protocol, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_republic_amif_agent_manager_interface_request_args_set_property (GObject *object,
                                                                          guint property_id,
                                                                          const GValue *value,
                                                                          GParamSpec *pspec)
{
  edu_rice_republic_amifAgentManagerInterfaceRequestArgs *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS_RQ:
      if (self->rq != NULL)
        g_object_unref (self->rq);
      self->rq = g_value_dup_object (value);
      self->__isset_rq = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_republic_amif_agent_manager_interface_request_args_get_property (GObject *object,
                                                                          guint property_id,
                                                                          GValue *value,
                                                                          GParamSpec *pspec)
{
  edu_rice_republic_amifAgentManagerInterfaceRequestArgs *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS_RQ:
      g_value_set_object (value, self->rq);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_republic_amif_agent_manager_interface_request_args_instance_init (edu_rice_republic_amifAgentManagerInterfaceRequestArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->rq = g_object_new (EDU_RICE_REPUBLIC_AMIF_TYPE_REQUEST, NULL);
  object->__isset_rq = FALSE;
}

static void 
edu_rice_republic_amif_agent_manager_interface_request_args_finalize (GObject *object)
{
  edu_rice_republic_amifAgentManagerInterfaceRequestArgs *tobject = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->rq != NULL)
  {
    g_object_unref(tobject->rq);
    tobject->rq = NULL;
  }
}

static void
edu_rice_republic_amif_agent_manager_interface_request_args_class_init (edu_rice_republic_amifAgentManagerInterfaceRequestArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_republic_amif_agent_manager_interface_request_args_read;
  struct_class->write = edu_rice_republic_amif_agent_manager_interface_request_args_write;

  gobject_class->finalize = edu_rice_republic_amif_agent_manager_interface_request_args_finalize;
  gobject_class->get_property = edu_rice_republic_amif_agent_manager_interface_request_args_get_property;
  gobject_class->set_property = edu_rice_republic_amif_agent_manager_interface_request_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS_RQ,
     g_param_spec_object ("rq",
                         NULL,
                         NULL,
                         EDU_RICE_REPUBLIC_AMIF_TYPE_REQUEST,
                         G_PARAM_READWRITE));
}

GType
edu_rice_republic_amif_agent_manager_interface_request_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_republic_amifAgentManagerInterfaceRequestArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_republic_amif_agent_manager_interface_request_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_republic_amifAgentManagerInterfaceRequestArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_republic_amif_agent_manager_interface_request_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_republic_amifAgentManagerInterfaceRequestArgsType",
                                   &type_info, 0);
  }

  return type;
}

enum _edu_rice_republic_amifAgentManagerInterfaceRequestResultProperties
{
  PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT_0,
  PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT_SUCCESS
};

/* reads a agent_manager_interface_request_result object */
static gint32
edu_rice_republic_amif_agent_manager_interface_request_result_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_republic_amifAgentManagerInterfaceRequestResult * this_object = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 0:
        if (ftype == T_STRUCT)
        {
          if ((ret = thrift_struct_read (THRIFT_STRUCT (this_object->success), protocol, error)) < 0)
          {
            return -1;
          }
          xfer += ret;
          this_object->__isset_success = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_republic_amif_agent_manager_interface_request_result_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_republic_amifAgentManagerInterfaceRequestResult * this_object = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "AgentManagerInterfaceRequestResult", error)) < 0)
    return -1;
  xfer += ret;
  if (this_object->__isset_success == TRUE) {
    if ((ret = thrift_protocol_write_field_begin (protocol, "success", T_STRUCT, 0, error)) < 0)
      return -1;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (this_object->success), protocol, error)) < 0)
      return -1;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_republic_amif_agent_manager_interface_request_result_set_property (GObject *object,
                                                                            guint property_id,
                                                                            const GValue *value,
                                                                            GParamSpec *pspec)
{
  edu_rice_republic_amifAgentManagerInterfaceRequestResult *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT_SUCCESS:
      if (self->success != NULL)
        g_object_unref (self->success);
      self->success = g_value_dup_object (value);
      self->__isset_success = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_republic_amif_agent_manager_interface_request_result_get_property (GObject *object,
                                                                            guint property_id,
                                                                            GValue *value,
                                                                            GParamSpec *pspec)
{
  edu_rice_republic_amifAgentManagerInterfaceRequestResult *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT_SUCCESS:
      g_value_set_object (value, self->success);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_republic_amif_agent_manager_interface_request_result_instance_init (edu_rice_republic_amifAgentManagerInterfaceRequestResult * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->success = g_object_new (EDU_RICE_REPUBLIC_AMIF_TYPE_RESPONSE, NULL);
  object->__isset_success = FALSE;
}

static void 
edu_rice_republic_amif_agent_manager_interface_request_result_finalize (GObject *object)
{
  edu_rice_republic_amifAgentManagerInterfaceRequestResult *tobject = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->success != NULL)
  {
    g_object_unref(tobject->success);
    tobject->success = NULL;
  }
}

static void
edu_rice_republic_amif_agent_manager_interface_request_result_class_init (edu_rice_republic_amifAgentManagerInterfaceRequestResultClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_republic_amif_agent_manager_interface_request_result_read;
  struct_class->write = edu_rice_republic_amif_agent_manager_interface_request_result_write;

  gobject_class->finalize = edu_rice_republic_amif_agent_manager_interface_request_result_finalize;
  gobject_class->get_property = edu_rice_republic_amif_agent_manager_interface_request_result_get_property;
  gobject_class->set_property = edu_rice_republic_amif_agent_manager_interface_request_result_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT_SUCCESS,
     g_param_spec_object ("success",
                         NULL,
                         NULL,
                         EDU_RICE_REPUBLIC_AMIF_TYPE_RESPONSE,
                         G_PARAM_READWRITE));
}

GType
edu_rice_republic_amif_agent_manager_interface_request_result_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_republic_amifAgentManagerInterfaceRequestResultClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_republic_amif_agent_manager_interface_request_result_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_republic_amifAgentManagerInterfaceRequestResult),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_republic_amif_agent_manager_interface_request_result_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_republic_amifAgentManagerInterfaceRequestResultType",
                                   &type_info, 0);
  }

  return type;
}

enum _edu_rice_republic_amifAgentManagerInterfaceReleaseArgsProperties
{
  PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS_0,
  PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS_RL
};

/* reads a agent_manager_interface_release_args object */
static gint32
edu_rice_republic_amif_agent_manager_interface_release_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_republic_amifAgentManagerInterfaceReleaseArgs * this_object = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRUCT)
        {
          if ((ret = thrift_struct_read (THRIFT_STRUCT (this_object->rl), protocol, error)) < 0)
          {
            return -1;
          }
          xfer += ret;
          this_object->__isset_rl = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_republic_amif_agent_manager_interface_release_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_republic_amifAgentManagerInterfaceReleaseArgs * this_object = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "AgentManagerInterfaceReleaseArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "rl", T_STRUCT, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_struct_write (THRIFT_STRUCT (this_object->rl), protocol, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_republic_amif_agent_manager_interface_release_args_set_property (GObject *object,
                                                                          guint property_id,
                                                                          const GValue *value,
                                                                          GParamSpec *pspec)
{
  edu_rice_republic_amifAgentManagerInterfaceReleaseArgs *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS_RL:
      if (self->rl != NULL)
        g_object_unref (self->rl);
      self->rl = g_value_dup_object (value);
      self->__isset_rl = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_republic_amif_agent_manager_interface_release_args_get_property (GObject *object,
                                                                          guint property_id,
                                                                          GValue *value,
                                                                          GParamSpec *pspec)
{
  edu_rice_republic_amifAgentManagerInterfaceReleaseArgs *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS_RL:
      g_value_set_object (value, self->rl);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_republic_amif_agent_manager_interface_release_args_instance_init (edu_rice_republic_amifAgentManagerInterfaceReleaseArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->rl = g_object_new (EDU_RICE_REPUBLIC_AMIF_TYPE_RELEASE, NULL);
  object->__isset_rl = FALSE;
}

static void 
edu_rice_republic_amif_agent_manager_interface_release_args_finalize (GObject *object)
{
  edu_rice_republic_amifAgentManagerInterfaceReleaseArgs *tobject = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->rl != NULL)
  {
    g_object_unref(tobject->rl);
    tobject->rl = NULL;
  }
}

static void
edu_rice_republic_amif_agent_manager_interface_release_args_class_init (edu_rice_republic_amifAgentManagerInterfaceReleaseArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_republic_amif_agent_manager_interface_release_args_read;
  struct_class->write = edu_rice_republic_amif_agent_manager_interface_release_args_write;

  gobject_class->finalize = edu_rice_republic_amif_agent_manager_interface_release_args_finalize;
  gobject_class->get_property = edu_rice_republic_amif_agent_manager_interface_release_args_get_property;
  gobject_class->set_property = edu_rice_republic_amif_agent_manager_interface_release_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS_RL,
     g_param_spec_object ("rl",
                         NULL,
                         NULL,
                         EDU_RICE_REPUBLIC_AMIF_TYPE_RELEASE,
                         G_PARAM_READWRITE));
}

GType
edu_rice_republic_amif_agent_manager_interface_release_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_republic_amifAgentManagerInterfaceReleaseArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_republic_amif_agent_manager_interface_release_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_republic_amifAgentManagerInterfaceReleaseArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_republic_amif_agent_manager_interface_release_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_republic_amifAgentManagerInterfaceReleaseArgsType",
                                   &type_info, 0);
  }

  return type;
}

