/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef EDU_RICE_REPUBLIC_AMIF_REPUBLIC_TYPES_H
#define EDU_RICE_REPUBLIC_AMIF_REPUBLIC_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>

/* custom thrift includes */

/* begin types */

enum _edu_rice_republic_amifResponseType {
  EDU_RICE_REPUBLIC_AMIF_RESPONSE_TYPE_ACCEPT = 0,
  EDU_RICE_REPUBLIC_AMIF_RESPONSE_TYPE_DENY = 1
};
typedef enum _edu_rice_republic_amifResponseType edu_rice_republic_amifResponseType;

/* return the name of the constant */
const char *
toString_ResponseType(int value); 

typedef gint64 edu_rice_republic_amifBytes;

typedef gchar * edu_rice_republic_amifAppID;

typedef gchar * edu_rice_republic_amifDataID;

typedef gchar * edu_rice_republic_amifServerID;

typedef gchar * edu_rice_republic_amifRequestID;

typedef gchar * edu_rice_republic_amifResponseID;

typedef gint64 edu_rice_republic_amifResponseCode;

/* struct Request */
struct _edu_rice_republic_amifRequest
{ 
  ThriftStruct parent; 

  /* public */
  gchar * rid;
  gboolean __isset_rid;
  gchar * aid;
  gboolean __isset_aid;
  gchar * did;
  gboolean __isset_did;
  gint64 datasize;
  gboolean __isset_datasize;
  gint64 remainingsize;
  gboolean __isset_remainingsize;
  gchar * sender;
  gboolean __isset_sender;
  GHashTable * receivers;
  gboolean __isset_receivers;
};
typedef struct _edu_rice_republic_amifRequest edu_rice_republic_amifRequest;

struct _edu_rice_republic_amifRequestClass
{
  ThriftStructClass parent;
};
typedef struct _edu_rice_republic_amifRequestClass edu_rice_republic_amifRequestClass;

GType edu_rice_republic_amif_request_get_type (void);
#define EDU_RICE_REPUBLIC_AMIF_TYPE_REQUEST (edu_rice_republic_amif_request_get_type())
#define EDU_RICE_REPUBLIC_AMIF_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_REQUEST, edu_rice_republic_amifRequest))
#define EDU_RICE_REPUBLIC_AMIF_REQUEST_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), EDU_RICE_REPUBLIC_AMIF__TYPE_REQUEST, edu_rice_republic_amifRequestClass))
#define EDU_RICE_REPUBLIC_AMIF_IS_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_REQUEST))
#define EDU_RICE_REPUBLIC_AMIF_IS_REQUEST_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), EDU_RICE_REPUBLIC_AMIF_TYPE_REQUEST))
#define EDU_RICE_REPUBLIC_AMIF_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_REQUEST, edu_rice_republic_amifRequestClass))

/* struct Response */
struct _edu_rice_republic_amifResponse
{ 
  ThriftStruct parent; 

  /* public */
  gchar * rid;
  gboolean __isset_rid;
  edu_rice_republic_amifResponseType type;
  gboolean __isset_type;
  gint64 code;
  gboolean __isset_code;
  gint64 acceptedsize;
  gboolean __isset_acceptedsize;
};
typedef struct _edu_rice_republic_amifResponse edu_rice_republic_amifResponse;

struct _edu_rice_republic_amifResponseClass
{
  ThriftStructClass parent;
};
typedef struct _edu_rice_republic_amifResponseClass edu_rice_republic_amifResponseClass;

GType edu_rice_republic_amif_response_get_type (void);
#define EDU_RICE_REPUBLIC_AMIF_TYPE_RESPONSE (edu_rice_republic_amif_response_get_type())
#define EDU_RICE_REPUBLIC_AMIF_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_RESPONSE, edu_rice_republic_amifResponse))
#define EDU_RICE_REPUBLIC_AMIF_RESPONSE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), EDU_RICE_REPUBLIC_AMIF__TYPE_RESPONSE, edu_rice_republic_amifResponseClass))
#define EDU_RICE_REPUBLIC_AMIF_IS_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_RESPONSE))
#define EDU_RICE_REPUBLIC_AMIF_IS_RESPONSE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), EDU_RICE_REPUBLIC_AMIF_TYPE_RESPONSE))
#define EDU_RICE_REPUBLIC_AMIF_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_RESPONSE, edu_rice_republic_amifResponseClass))

/* struct Release */
struct _edu_rice_republic_amifRelease
{ 
  ThriftStruct parent; 

  /* public */
  gchar * rid;
  gboolean __isset_rid;
};
typedef struct _edu_rice_republic_amifRelease edu_rice_republic_amifRelease;

struct _edu_rice_republic_amifReleaseClass
{
  ThriftStructClass parent;
};
typedef struct _edu_rice_republic_amifReleaseClass edu_rice_republic_amifReleaseClass;

GType edu_rice_republic_amif_release_get_type (void);
#define EDU_RICE_REPUBLIC_AMIF_TYPE_RELEASE (edu_rice_republic_amif_release_get_type())
#define EDU_RICE_REPUBLIC_AMIF_RELEASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_RELEASE, edu_rice_republic_amifRelease))
#define EDU_RICE_REPUBLIC_AMIF_RELEASE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), EDU_RICE_REPUBLIC_AMIF__TYPE_RELEASE, edu_rice_republic_amifReleaseClass))
#define EDU_RICE_REPUBLIC_AMIF_IS_RELEASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_RELEASE))
#define EDU_RICE_REPUBLIC_AMIF_IS_RELEASE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), EDU_RICE_REPUBLIC_AMIF_TYPE_RELEASE))
#define EDU_RICE_REPUBLIC_AMIF_RELEASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_RELEASE, edu_rice_republic_amifReleaseClass))

/* constants */

/* struct AgentManagerInterfaceRequestArgs */
struct _edu_rice_republic_amifAgentManagerInterfaceRequestArgs
{ 
  ThriftStruct parent; 

  /* public */
  edu_rice_republic_amifRequest * rq;
  gboolean __isset_rq;
};
typedef struct _edu_rice_republic_amifAgentManagerInterfaceRequestArgs edu_rice_republic_amifAgentManagerInterfaceRequestArgs;

struct _edu_rice_republic_amifAgentManagerInterfaceRequestArgsClass
{
  ThriftStructClass parent;
};
typedef struct _edu_rice_republic_amifAgentManagerInterfaceRequestArgsClass edu_rice_republic_amifAgentManagerInterfaceRequestArgsClass;

GType edu_rice_republic_amif_agent_manager_interface_request_args_get_type (void);
#define EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_ARGS (edu_rice_republic_amif_agent_manager_interface_request_args_get_type())
#define EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_ARGS, edu_rice_republic_amifAgentManagerInterfaceRequestArgs))
#define EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), EDU_RICE_REPUBLIC_AMIF__TYPE_AGENT_MANAGER_INTERFACE_REQUEST_ARGS, edu_rice_republic_amifAgentManagerInterfaceRequestArgsClass))
#define EDU_RICE_REPUBLIC_AMIF_IS_AGENT_MANAGER_INTERFACE_REQUEST_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_ARGS))
#define EDU_RICE_REPUBLIC_AMIF_IS_AGENT_MANAGER_INTERFACE_REQUEST_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_ARGS))
#define EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_ARGS, edu_rice_republic_amifAgentManagerInterfaceRequestArgsClass))

/* struct AgentManagerInterfaceRequestResult */
struct _edu_rice_republic_amifAgentManagerInterfaceRequestResult
{ 
  ThriftStruct parent; 

  /* public */
  edu_rice_republic_amifResponse * success;
  gboolean __isset_success;
};
typedef struct _edu_rice_republic_amifAgentManagerInterfaceRequestResult edu_rice_republic_amifAgentManagerInterfaceRequestResult;

struct _edu_rice_republic_amifAgentManagerInterfaceRequestResultClass
{
  ThriftStructClass parent;
};
typedef struct _edu_rice_republic_amifAgentManagerInterfaceRequestResultClass edu_rice_republic_amifAgentManagerInterfaceRequestResultClass;

GType edu_rice_republic_amif_agent_manager_interface_request_result_get_type (void);
#define EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_RESULT (edu_rice_republic_amif_agent_manager_interface_request_result_get_type())
#define EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_RESULT, edu_rice_republic_amifAgentManagerInterfaceRequestResult))
#define EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), EDU_RICE_REPUBLIC_AMIF__TYPE_AGENT_MANAGER_INTERFACE_REQUEST_RESULT, edu_rice_republic_amifAgentManagerInterfaceRequestResultClass))
#define EDU_RICE_REPUBLIC_AMIF_IS_AGENT_MANAGER_INTERFACE_REQUEST_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_RESULT))
#define EDU_RICE_REPUBLIC_AMIF_IS_AGENT_MANAGER_INTERFACE_REQUEST_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_RESULT))
#define EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_REQUEST_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_RESULT, edu_rice_republic_amifAgentManagerInterfaceRequestResultClass))

/* struct AgentManagerInterfaceReleaseArgs */
struct _edu_rice_republic_amifAgentManagerInterfaceReleaseArgs
{ 
  ThriftStruct parent; 

  /* public */
  edu_rice_republic_amifRelease * rl;
  gboolean __isset_rl;
};
typedef struct _edu_rice_republic_amifAgentManagerInterfaceReleaseArgs edu_rice_republic_amifAgentManagerInterfaceReleaseArgs;

struct _edu_rice_republic_amifAgentManagerInterfaceReleaseArgsClass
{
  ThriftStructClass parent;
};
typedef struct _edu_rice_republic_amifAgentManagerInterfaceReleaseArgsClass edu_rice_republic_amifAgentManagerInterfaceReleaseArgsClass;

GType edu_rice_republic_amif_agent_manager_interface_release_args_get_type (void);
#define EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_RELEASE_ARGS (edu_rice_republic_amif_agent_manager_interface_release_args_get_type())
#define EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_RELEASE_ARGS, edu_rice_republic_amifAgentManagerInterfaceReleaseArgs))
#define EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), EDU_RICE_REPUBLIC_AMIF__TYPE_AGENT_MANAGER_INTERFACE_RELEASE_ARGS, edu_rice_republic_amifAgentManagerInterfaceReleaseArgsClass))
#define EDU_RICE_REPUBLIC_AMIF_IS_AGENT_MANAGER_INTERFACE_RELEASE_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_RELEASE_ARGS))
#define EDU_RICE_REPUBLIC_AMIF_IS_AGENT_MANAGER_INTERFACE_RELEASE_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_RELEASE_ARGS))
#define EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_RELEASE_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_RELEASE_ARGS, edu_rice_republic_amifAgentManagerInterfaceReleaseArgsClass))

#endif /* EDU_RICE_REPUBLIC_AMIF_REPUBLIC_TYPES_H */
