/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "edu_rice_republic_amif_agent_manager_interface.h"

gboolean
edu_rice_republic_amif_agent_manager_interface_if_request (edu_rice_republic_amifAgentManagerInterfaceIf *iface, edu_rice_republic_amifResponse ** _return, const edu_rice_republic_amifRequest * rq, GError **error)
{
  return EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_IF_GET_INTERFACE (iface)->request (iface, _return, rq, error);
}

gboolean
edu_rice_republic_amif_agent_manager_interface_if_release (edu_rice_republic_amifAgentManagerInterfaceIf *iface, const edu_rice_republic_amifRelease * rl, GError **error)
{
  return EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_IF_GET_INTERFACE (iface)->release (iface, rl, error);
}

GType
edu_rice_republic_amif_agent_manager_interface_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (edu_rice_republic_amifAgentManagerInterfaceIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "edu_rice_republic_amifAgentManagerInterfaceIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
edu_rice_republic_amif_agent_manager_interface_if_interface_init (edu_rice_republic_amifAgentManagerInterfaceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (edu_rice_republic_amifAgentManagerInterfaceClient, edu_rice_republic_amif_agent_manager_interface_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_IF,
                                                edu_rice_republic_amif_agent_manager_interface_if_interface_init))

enum _edu_rice_republic_amifAgentManagerInterfaceClientProperties
{
  PROP_0,
  PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT_INPUT_PROTOCOL,
  PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT_OUTPUT_PROTOCOL
};

void
edu_rice_republic_amif_agent_manager_interface_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  edu_rice_republic_amifAgentManagerInterfaceClient *client = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
edu_rice_republic_amif_agent_manager_interface_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  edu_rice_republic_amifAgentManagerInterfaceClient *client = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean edu_rice_republic_amif_agent_manager_interface_client_send_request (edu_rice_republic_amifAgentManagerInterfaceIf * iface, const edu_rice_republic_amifRequest * rq, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "request", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "request_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "rq", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (rq), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean edu_rice_republic_amif_agent_manager_interface_client_recv_request (edu_rice_republic_amifAgentManagerInterfaceIf * iface, edu_rice_republic_amifResponse ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "request", 7) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected request", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean edu_rice_republic_amif_agent_manager_interface_client_request (edu_rice_republic_amifAgentManagerInterfaceIf * iface, edu_rice_republic_amifResponse ** _return, const edu_rice_republic_amifRequest * rq, GError ** error)
{
  if (!edu_rice_republic_amif_agent_manager_interface_client_send_request (iface, rq, error))
    return FALSE;
  if (!edu_rice_republic_amif_agent_manager_interface_client_recv_request (iface, _return, error))
    return FALSE;
  return TRUE;
}

gboolean edu_rice_republic_amif_agent_manager_interface_client_send_release (edu_rice_republic_amifAgentManagerInterfaceIf * iface, const edu_rice_republic_amifRelease * rl, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "release", T_ONEWAY, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "release_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "rl", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (rl), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean edu_rice_republic_amif_agent_manager_interface_client_release (edu_rice_republic_amifAgentManagerInterfaceIf * iface, const edu_rice_republic_amifRelease * rl, GError ** error)
{
  if (!edu_rice_republic_amif_agent_manager_interface_client_send_release (iface, rl, error))
    return FALSE;
  return TRUE;
}

static void
edu_rice_republic_amif_agent_manager_interface_if_interface_init (edu_rice_republic_amifAgentManagerInterfaceIfInterface *iface)
{
  iface->request = edu_rice_republic_amif_agent_manager_interface_client_request;
  iface->release = edu_rice_republic_amif_agent_manager_interface_client_release;
}

static void
edu_rice_republic_amif_agent_manager_interface_client_init (edu_rice_republic_amifAgentManagerInterfaceClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
edu_rice_republic_amif_agent_manager_interface_client_class_init (edu_rice_republic_amifAgentManagerInterfaceClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = edu_rice_republic_amif_agent_manager_interface_client_set_property;
  gobject_class->get_property = edu_rice_republic_amif_agent_manager_interface_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
edu_rice_republic_amif_agent_manager_interface_handler_agent_manager_interface_if_interface_init (edu_rice_republic_amifAgentManagerInterfaceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (edu_rice_republic_amifAgentManagerInterfaceHandler, 
                         edu_rice_republic_amif_agent_manager_interface_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_IF,
                                                edu_rice_republic_amif_agent_manager_interface_handler_agent_manager_interface_if_interface_init))

gboolean edu_rice_republic_amif_agent_manager_interface_handler_request (edu_rice_republic_amifAgentManagerInterfaceIf * iface, edu_rice_republic_amifResponse ** _return, const edu_rice_republic_amifRequest * rq, GError ** error)
{
  g_return_val_if_fail (EDU_RICE_REPUBLIC_AMIF_IS_AGENT_MANAGER_INTERFACE_HANDLER (iface), FALSE);

  return EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_HANDLER_GET_CLASS (iface)->request (iface, _return, rq, error);
}

gboolean edu_rice_republic_amif_agent_manager_interface_handler_release (edu_rice_republic_amifAgentManagerInterfaceIf * iface, const edu_rice_republic_amifRelease * rl, GError ** error)
{
  g_return_val_if_fail (EDU_RICE_REPUBLIC_AMIF_IS_AGENT_MANAGER_INTERFACE_HANDLER (iface), FALSE);

  return EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_HANDLER_GET_CLASS (iface)->release (iface, rl, error);
}

static void
edu_rice_republic_amif_agent_manager_interface_handler_agent_manager_interface_if_interface_init (edu_rice_republic_amifAgentManagerInterfaceIfInterface *iface)
{
  iface->request = edu_rice_republic_amif_agent_manager_interface_handler_request;
  iface->release = edu_rice_republic_amif_agent_manager_interface_handler_release;
}

static void
edu_rice_republic_amif_agent_manager_interface_handler_init (edu_rice_republic_amifAgentManagerInterfaceHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
edu_rice_republic_amif_agent_manager_interface_handler_class_init (edu_rice_republic_amifAgentManagerInterfaceHandlerClass *cls)
{
  cls->request = NULL;
  cls->release = NULL;
}

enum _edu_rice_republic_amifAgentManagerInterfaceProcessorProperties
{
  PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR_0,
  PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (edu_rice_republic_amifAgentManagerInterfaceProcessor,
               edu_rice_republic_amif_agent_manager_interface_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* edu_rice_republic_amifAgentManagerInterfaceProcessorProcessFunction) (edu_rice_republic_amifAgentManagerInterfaceProcessor *, 
                                                                                          gint32,
                                                                                          ThriftProtocol *,
                                                                                          ThriftProtocol *,
                                                                                          GError **);

typedef struct
{
  gchar *name;
  edu_rice_republic_amifAgentManagerInterfaceProcessorProcessFunction function;
} edu_rice_republic_amif_agent_manager_interface_processor_process_function_def;

static gboolean
edu_rice_republic_amif_agent_manager_interface_processor_process_request (edu_rice_republic_amifAgentManagerInterfaceProcessor *,
                                                                          gint32,
                                                                          ThriftProtocol *,
                                                                          ThriftProtocol *,
                                                                          GError **);
static gboolean
edu_rice_republic_amif_agent_manager_interface_processor_process_release (edu_rice_republic_amifAgentManagerInterfaceProcessor *,
                                                                          gint32,
                                                                          ThriftProtocol *,
                                                                          ThriftProtocol *,
                                                                          GError **);

static edu_rice_republic_amif_agent_manager_interface_processor_process_function_def
edu_rice_republic_amif_agent_manager_interface_processor_process_function_defs[2] = {
  {
    "request",
    edu_rice_republic_amif_agent_manager_interface_processor_process_request
  },
  {
    "release",
    edu_rice_republic_amif_agent_manager_interface_processor_process_release
  }
};

static gboolean
edu_rice_republic_amif_agent_manager_interface_processor_process_request (edu_rice_republic_amifAgentManagerInterfaceProcessor *self,
                                                                          gint32 sequence_id,
                                                                          ThriftProtocol *input_protocol,
                                                                          ThriftProtocol *output_protocol,
                                                                          GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  edu_rice_republic_amifAgentManagerInterfaceRequestArgs * args =
    g_object_new (EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    edu_rice_republic_amifRequest * rq;
    edu_rice_republic_amifResponse * return_value;
    edu_rice_republic_amifAgentManagerInterfaceRequestResult * result_struct;

    g_object_get (args,
                  "rq", &rq,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_REQUEST_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (edu_rice_republic_amif_agent_manager_interface_handler_request (EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_IF (self->handler),
                                                                        &return_value,
                                                                        rq,
                                                                        error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "request",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("AgentManagerInterface.request implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "request",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (rq != NULL)
      g_object_unref (rq);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
edu_rice_republic_amif_agent_manager_interface_processor_process_release (edu_rice_republic_amifAgentManagerInterfaceProcessor *self,
                                                                          gint32 sequence_id,
                                                                          ThriftProtocol *input_protocol,
                                                                          ThriftProtocol *output_protocol,
                                                                          GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  edu_rice_republic_amifAgentManagerInterfaceReleaseArgs * args =
    g_object_new (EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_RELEASE_ARGS, NULL);

  THRIFT_UNUSED_VAR (sequence_id);
  THRIFT_UNUSED_VAR (output_protocol);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    edu_rice_republic_amifRelease * rl;

    g_object_get (args,
                  "rl", &rl,
                  NULL);

    if (edu_rice_republic_amif_agent_manager_interface_handler_release (EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_IF (self->handler),
                                                                        rl,
                                                                        error) == TRUE)
    {
    }
    else
    {
      if (*error == NULL)
        g_warning ("AgentManagerInterface.release implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "release",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (rl != NULL)
      g_object_unref (rl);
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
edu_rice_republic_amif_agent_manager_interface_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                                                        ThriftProtocol *input_protocol,
                                                                        ThriftProtocol *output_protocol,
                                                                        gchar *method_name,
                                                                        gint32 sequence_id,
                                                                        GError **error)
{
  edu_rice_republic_amif_agent_manager_interface_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  edu_rice_republic_amifAgentManagerInterfaceProcessor *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
edu_rice_republic_amif_agent_manager_interface_processor_set_property (GObject *object,
                                                                       guint property_id,
                                                                       const GValue *value,
                                                                       GParamSpec *pspec)
{
  edu_rice_republic_amifAgentManagerInterfaceProcessor *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_republic_amif_agent_manager_interface_processor_get_property (GObject *object,
                                                                       guint property_id,
                                                                       GValue *value,
                                                                       GParamSpec *pspec)
{
  edu_rice_republic_amifAgentManagerInterfaceProcessor *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_republic_amif_agent_manager_interface_processor_dispose (GObject *gobject)
{
  edu_rice_republic_amifAgentManagerInterfaceProcessor *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (edu_rice_republic_amif_agent_manager_interface_processor_parent_class)->dispose (gobject);
}

static void
edu_rice_republic_amif_agent_manager_interface_processor_finalize (GObject *gobject)
{
  edu_rice_republic_amifAgentManagerInterfaceProcessor *self = EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR (gobject);

  g_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (edu_rice_republic_amif_agent_manager_interface_processor_parent_class)->finalize (gobject);
}

static void
edu_rice_republic_amif_agent_manager_interface_processor_init (edu_rice_republic_amifAgentManagerInterfaceProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 2; index += 1)
    g_hash_table_insert (self->process_map,
                         edu_rice_republic_amif_agent_manager_interface_processor_process_function_defs[index].name,
                         &edu_rice_republic_amif_agent_manager_interface_processor_process_function_defs[index]);
}

static void
edu_rice_republic_amif_agent_manager_interface_processor_class_init (edu_rice_republic_amifAgentManagerInterfaceProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = edu_rice_republic_amif_agent_manager_interface_processor_dispose;
  gobject_class->finalize = edu_rice_republic_amif_agent_manager_interface_processor_finalize;
  gobject_class->set_property = edu_rice_republic_amif_agent_manager_interface_processor_set_property;
  gobject_class->get_property = edu_rice_republic_amif_agent_manager_interface_processor_get_property;

  dispatch_processor_class->dispatch_call = edu_rice_republic_amif_agent_manager_interface_processor_dispatch_call;
  cls->dispatch_call = edu_rice_republic_amif_agent_manager_interface_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    EDU_RICE_REPUBLIC_AMIF_TYPE_AGENT_MANAGER_INTERFACE_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_EDU_RICE_REPUBLIC_AMIF_AGENT_MANAGER_INTERFACE_PROCESSOR_HANDLER,
                                   param_spec);
}
