/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.rice.bold.service;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * you can define enums, which are just 32 bit integers. values are optional
 * and start at 1 if not supplied, c style again.
 */
public enum PushReplyCmd implements org.apache.thrift.TEnum {
  PUSH(0),
  POSTPONE(1),
  DENY(2);

  private final int value;

  private PushReplyCmd(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PushReplyCmd findByValue(int value) { 
    switch (value) {
      case 0:
        return PUSH;
      case 1:
        return POSTPONE;
      case 2:
        return DENY;
      default:
        return null;
    }
  }
}
